In [1]:
import os
import torch
import yaml
import sys

MULTIPOLY_FOLDER = os.path.dirname(os.path.dirname(os.getcwd()))

sys.path.append(MULTIPOLY_FOLDER)


In [2]:
from src.data.utils import midi_to_npz, chd_to_midi_file


/root/miniconda3/envs/poly/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)


In [3]:
npz_dict = midi_to_npz("test_data/0.mid","test_data/0.out")

In [4]:
print(npz_dict["db_pos"])


[   0   16   32   48   64   80   96  112  128  144  160  176  192  208
  224  240  256  272  288  304  320  336  352  368  384  400  416  432
  448  464  480  496  512  528  544  560  576  592  608  624  640  656
  672  688  704  720  736  752  768  784  800  816  832  848  864  880
  896  912  928  944  960  976  992 1008 1024 1040 1056 1072 1088 1104
 1120 1136 1152 1168 1184 1200 1216 1232 1248 1264 1280 1296 1312 1328
 1344 1360 1376 1392 1408 1424 1440 1456 1472 1488 1504 1520 1536 1552
 1568 1584 1600 1616 1632 1648 1664 1680 1696 1712 1728 1744 1760 1776
 1792 1808 1824]


In [5]:
import numpy as np
from tqdm import tqdm

np.savez("test_data/0.npz",**npz_dict)

In [6]:
npz_file = np.load("test_data/0.npz")

In [7]:
print(npz_file["db_pos_filter"].shape)

(115,)


In [ ]:
chord = npz_file["chord"]
print(chord.shape)
chd_to_midi_file(chord,"test_data/chord_recon.mid")



(457, 36)


In [ ]:
notes = npz_file["notes"]
print(notes) #onset pitch duration track

[[  16   57    1    1]
 [  16   69    1    3]
 [  18   57    1    1]
 ...
 [1824   57    2    3]
 [1824   69    1    3]
 [1824   81    1    3]]


In [11]:
import muspy
tracks = [muspy.Track(24),muspy.Track(36),muspy.Track(0),muspy.Track(48)]

for note in notes:
    curr_note = muspy.Note(note[0],note[1],note[2])
    tracks[note[3]].notes.append(curr_note)
music = muspy.Music(resolution=4,tempos=[muspy.Tempo(0,120)],time_signatures=[muspy.TimeSignature(0,4,4)])
music.tracks = tracks
music.write_midi("test_data/recon.mid")

In [ ]:
npz_dict = midi_to_npz("test_data/0.mid","test_data/0.out")
np.savez("test_data/0.npz",**npz_dict)
os.remove("test_data/0.out")

In [ ]:
data_folder = r"/root/autodl-tmp/multipoly/data/lmd/lpd_5_midi/"
data_fpaths = os.listdir(data_folder)
problems = []
from tqdm import tqdm
for i in tqdm(range(len(data_fpaths))):
    try:
        midi_fpath = os.path.join(data_folder,f"{i}.mid")
        chord_fpath = os.path.join(data_folder,f"{i}.out")
        npz_fpath = os.path.join(data_folder,f"{i}.npz")
        npz_dict = midi_to_npz(midi_fpath, chord_fpath)
        np.savez(npz_fpath, **npz_dict)
        os.remove(chord_fpath)
    except:
        problems.append(i)
print(problems)



  0%|          | 0/21611 [00:00<?, ?it/s]

100%|██████████| 21611/21611 [2:04:23<00:00,  2.90it/s]  

[186, 1424, 1807, 1822, 2242, 2297, 3387, 3524, 4683, 5181, 5264, 5770, 5799, 6691, 6696, 6753, 7706, 8580, 9733, 9942, 10373, 10844, 11100, 11127, 12968, 13310, 13670, 13889, 14635, 14841, 14844, 15280, 15754, 16071, 16422, 16445, 16468, 16600, 16912, 17063, 17169, 17957, 18500, 18507, 20103, 20467, 21425, 21426, 21427, 21428, 21429, 21430, 21431, 21432, 21433, 21434, 21435, 21436, 21437, 21438, 21439, 21440, 21441, 21442, 21443, 21444, 21445, 21446, 21447, 21448, 21449, 21450, 21451, 21452, 21453, 21454, 21455, 21456, 21457, 21458, 21459, 21460, 21461, 21462, 21463, 21464, 21465, 21466, 21467, 21468, 21469, 21470, 21471, 21472, 21473, 21474, 21475, 21476, 21477, 21478, 21479, 21480, 21481, 21482, 21483, 21484, 21485, 21486, 21487, 21488, 21489, 21490, 21491, 21492, 21493, 21494, 21495, 21496, 21497, 21498, 21499, 21500, 21501, 21502, 21503, 21504, 21505, 21506, 21507, 21508, 21509, 21510, 21511, 21512, 21513, 21514, 21515, 21516, 21517, 21518, 21519, 21520, 21521, 21522, 21523, 21524

In [17]:


print(len(problems))

232
