import torch
from einops import rearrange

In [1]:
import torch
from einops import rearrange

In [5]:
x = torch.arange(0,12).reshape(3,4,1)
print(x)

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]])


In [6]:
x = rearrange(x, "b t c -> (b t) c")
print(x)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])


In [8]:
t = torch.randint(0,20,[3,])
print(t)
print(t.shape)

tensor([19,  0,  8])
torch.Size([3])


In [13]:
t = t.reshape(-1,1)

ts = torch.cat([t]*4,dim=1)
print(ts)
print(ts.shape)

tensor([[19, 19, 19, 19],
        [ 0,  0,  0,  0],
        [ 8,  8,  8,  8]])
torch.Size([3, 4])


In [14]:
cond = torch.rand(7,1,512)

cond_cat = torch.cat([cond]*4, dim=1).reshape(-1,1,512)


In [15]:
print(cond_cat.shape)

torch.Size([28, 1, 512])


In [16]:
print(cond_cat)

tensor([[[0.9196, 0.8811, 0.0524,  ..., 0.1269, 0.3690, 0.6117]],

        [[0.9196, 0.8811, 0.0524,  ..., 0.1269, 0.3690, 0.6117]],

        [[0.9196, 0.8811, 0.0524,  ..., 0.1269, 0.3690, 0.6117]],

        ...,

        [[0.9853, 0.2799, 0.1747,  ..., 0.9651, 0.6864, 0.8785]],

        [[0.9853, 0.2799, 0.1747,  ..., 0.9651, 0.6864, 0.8785]],

        [[0.9853, 0.2799, 0.1747,  ..., 0.9651, 0.6864, 0.8785]]])
